Support reporting metrics to prometheus
flink-extended/flink-remote-shuffle pull request #21
Opened 2021-12-10 08:30 UTC by jlon

## What is the purpose of the change
Support reporting metrics to prometheus.(use PrometheusReporter or use PrometheusPushGatewayReporter)

## Instructions for use
Put the following configuration into the global configuration.
- remote-shuffle.metrics.reporter.promgateway.factory.class: com.alibaba.flink.shuffle.metrics.reporter.PrometheusPushGatewayReporterFactory
- remote-shuffle.metrics.reporter.promgateway.host: xxxxxx
- remote-shuffle.metrics.reporter.promgateway.port: 9091
- remote-shuffle.metrics.reporter.promgateway.jobName: flink-remote-shuffle
- remote-shuffle.metrics.reporter.promgateway.randomJobNameSuffix: true
- remote-shuffle.metrics.reporter.promgateway.deleteOnShutdown: false
- remote-shuffle.metrics.reporter.promgateway.interval: 60 SECONDS

2021-12-14 08:18 UTC, wsry commented
This is big change. I will take a look.

2022-03-09 07:37 UTC, wsry requested changes
@jlon Thanks for the contribution. I have left some comments.

2022-03-09 07:37 UTC, wsry commented on shuffle-metrics-reporter/shuffle-metrics-reporter-prometheus/src/main/java/com/alibaba/flink/shuffle/metrics/reporter/AbstractPrometheusReporter.java
> +                return meter.getCount();
I think we should use getOneMinuteRate here?

2022-03-09 07:37 UTC, wsry commented on shuffle-metrics-reporter/shuffle-metrics-reporter-prometheus/src/main/java/com/alibaba/flink/shuffle/metrics/reporter/AbstractPrometheusReporter.java
> +                                        filterCharacters(
It seems we will always filter the invalid character, if so, should we remove the FILTER_LABEL_VALUE_CHARACTER config option?

2022-03-09 07:37 UTC, wsry commented on shuffle-metrics-reporter/shuffle-metrics-reporter-prometheus/src/main/java/com/alibaba/flink/shuffle/metrics/reporter/AbstractPrometheusReporter.java
> +    private String getGroupByMetricName(
This is a suboptimal implementation. As discussed above, if the metric name already contains the group name, this is not needed.

2022-04-15 02:40 UTC, dangshazi commented on shuffle-core/src/main/java/com/alibaba/flink/shuffle/core/utils/NetUtils.java
> +    public static Iterator<Integer> getPortRangeFromString(String rangeDefinition)
I think we should support multiple port ranges in case ShuffleManager & ShuffleWorker Run in same node

2022-04-15 03:48 UTC, dangshazi commented on shuffle-metrics-reporter/shuffle-metrics-reporter-prometheus/src/main/java/com/alibaba/flink/shuffle/metrics/reporter/PrometheusReporter.java
> +public class PrometheusReporter extends AbstractPrometheusReporter {
No, we can't.

HTTPServer exports metrics using Prometheus format in poll mode

2022-04-29 05:42 UTC, wsry commented
As this PR has no update for a long time. Let's move the discussion to https://github.com/flink-extended/flink-remote-shuffle/pull/64.

2022-04-29 05:42 UTC, closed without merging